server:
  port: 8084
  
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/department/**
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/rating/**
 