server:
  port: 8085
  
spring:
  application:
    name: Product-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice1
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost